version: "3"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - /home:/LLM_application_chatbot/data
    environment:
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}

volumes:
  conversations_data: