apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-deployment
  labels:
    app: chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - name: chatbot
        image: jabural/chatbot:latest
        ports:
        - containerPort: 8000
    env:
      - name: HUGGINGFACE_HUB_TOKEN
        valueFrom:
          secretKeyRef:
            name: huggingface-secret
            key: HUGGINGFACE_HUB_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
spec:
  type: NodePort
  selector:
    app: chatbot
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30100