version: "3"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./main.py:/LLM_application_chatbot/main.py
    environment:
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}